"""
Django settings for cliente_login_unico_govbr_django project.

Generated by 'django-admin startproject' using Django 2.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'flfknlq=a+2$i#v8#a)n87p5i9!mtzz=wk^g*^@(9_a((69vc&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cliente_login_unico_govbr_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cliente_login_unico_govbr_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = (
    'govbr_backend.backends.GovbrOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = '/'


# GOV BR OATU2 PROVIDER
SOCIAL_AUTH_GOVBR_KEY = ''  #INFORME O CLIENT ID RECEBIDO DA SGD/LOGIN UNICO
SOCIAL_AUTH_GOVBR_SECRET = '' #INFORME O CLIENT SECRET RECEBIDO DA SGD/LOGIN UNICO
SOCIAL_AUTH_GOVBR_SCOPE = ['openid', 'profile', 'phone', 'email']
SOCIAL_AUTH_GOVBR_EXTRA_DATA = ['name', 'phone_number', 'username', 'email']


#Defina como True para forçar https na redirect_uri
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False

#NOTE: AS URLS abaixo refrem-se ao ambiente de Staging do Login Único
# cliente_govbr settings
AUTHORIZATION_URL = 'https://sso.staging.acesso.gov.br/authorize'
ACCESS_TOKEN_URL = 'https://sso.staging.acesso.gov.br/token'
USER_DATA_URL = 'https://sso.staging.acesso.gov.br/userinfo'

# urls govbr
LOGOUT_URL_GOV_BR = 'https://sso.staging.acesso.gov.br/logout?post_logout_redirect_uri=http://localhost:8000'
ALTERAR_PERFIL_URL_GOV_BR = 'https://staging.acesso.gov.br/area-cidadao/#/alterarCadastro'
ALTERAR_SENHA_URL_GOV_BR = 'https://staging.acesso.gov.br/area-cidadao/#/alterarSenha'
